# Generated by Django 5.2.3 on 2025-06-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichaje',
            name='hora_entrada',
        ),
        migrations.RemoveField(
            model_name='fichaje',
            name='hora_salida',
        ),
        migrations.AddField(
            model_name='fichaje',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaje',
            name='tipo',
            field=models.CharField(default='entrada', max_length=50),
        ),
    ]
