# Generated by Django 5.2.3 on 2025-07-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_fichaje_hora_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='descripcion',
            field=models.CharField(default='Departamento creado sin descripción', max_length=255),
        ),
        migrations.AlterField(
            model_name='fichaje',
            name='fecha',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='fichaje',
            name='hora',
            field=models.TimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='fichaje',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10),
        ),
    ]
